import type { Locale } from "@/lib/constants";

export type CommerceCopy = {
  catalog: {
    metaTitle: string;
    metaDescription: string;
    eyebrow: string;
    title: string;
    body: string;
    results: string;
    configuredTitle: string;
    configuredBody: string;
    errorTitle: string;
    errorBody: string;
    emptyTitle: string;
    emptyBody: string;
    filters: {
      searchLabel: string;
      searchPlaceholder: string;
      brand: string;
      allBrands: string;
      category: string;
      allCategories: string;
      availability: string;
      anyStock: string;
      inStock: string;
      limited: string;
      quote: string;
      condition: string;
      anyCondition: string;
      new: string;
      refurbished: string;
      surplus: string;
      sort: string;
      relevance: string;
      alphabetical: string;
      price: string;
      search: string;
      clear: string;
    };
    pagination: {
      label: string;
      previous: string;
      next: string;
    };
  };
  product: {
    product: string;
    publishedProduct: string;
    requestQuote: string;
    contactTeam: string;
    configuredTitle: string;
    configuredBody: string;
    errorTitle: string;
    referencePhoto: string;
    technicalSpecifications: string;
    specificationsPending: string;
    estimatedPrice: string;
    estimatedPriceBody: string;
    featured: string;
    fallbackDescription: string;
    priceByQuote: string;
    stock: string;
    verify: string;
    condition: string;
    packaging: string;
    origin: string;
    leadTime: string;
    days: string;
    view: string;
    add: string;
    addToCart: string;
    saveFavorite: string;
    compare: string;
    datasheet: string;
    viewSource: string;
    share: string;
  };
  cart: {
    label: string;
    eyebrow: string;
    title: string;
    body: string;
    added: string;
    emptyTitle: string;
    emptyBody: string;
    continueShopping: string;
    quantity: string;
    remove: string;
    estimatedSubtotal: string;
    quoteRequired: string;
    item: string;
    items: string;
    formTitle: string;
    formBody: string;
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    company: string;
    country: string;
    address: string;
    city: string;
    postalCode: string;
    notes: string;
    submit: string;
    success: string;
  };
};

const en: CommerceCopy = {
  catalog: {
    metaTitle: "Quicksol Global Catalog",
    metaDescription:
      "Search published electronic components by MPN, SKU, brand, category and availability.",
    eyebrow: "Products",
    title: "Electronic components catalog",
    body: "Explore 500 real manufacturer references. Unit prices are market estimates and are confirmed by quotation.",
    results: "results",
    configuredTitle: "Catalog configuration required",
    configuredBody:
      "The product catalog is temporarily unavailable. Please try again shortly.",
    errorTitle: "Catalog could not be loaded",
    errorBody:
      "The catalog service is temporarily unavailable. Try again or send an RFQ with the exact manufacturer part number.",
    emptyTitle: "No products match this search",
    emptyBody:
      "Clear one or more filters or request a quote for the exact manufacturer part number.",
    filters: {
      searchLabel: "Search catalog",
      searchPlaceholder: "Search MPN, SKU or manufacturer",
      brand: "Brand",
      allBrands: "All brands",
      category: "Category",
      allCategories: "All categories",
      availability: "Availability",
      anyStock: "Any stock",
      inStock: "In stock",
      limited: "Limited",
      quote: "On request",
      condition: "Condition",
      anyCondition: "Any condition",
      new: "New",
      refurbished: "Refurbished",
      surplus: "Surplus",
      sort: "Sort",
      relevance: "Relevance",
      alphabetical: "Alphabetical",
      price: "Price",
      search: "Search",
      clear: "Clear",
    },
    pagination: {
      label: "Catalog pagination",
      previous: "Previous",
      next: "Next",
    },
  },
  product: {
    product: "Product",
    publishedProduct: "Published catalog product.",
    requestQuote: "Request quote",
    contactTeam: "Contact team",
    configuredTitle: "Catalog configuration required",
    configuredBody:
      "Product details are temporarily unavailable. Please try again shortly.",
    errorTitle: "Product could not be loaded",
    referencePhoto: "Real package reference photo",
    technicalSpecifications: "Technical specifications",
    specificationsPending:
      "Specifications are not published yet. Request a quote for verified technical details.",
    estimatedPrice: "Estimated unit price",
    estimatedPriceBody:
      "Estimated USD unit price. Confirm final price, stock and freight by quotation.",
    featured: "Featured",
    fallbackDescription: "Technical details available on request.",
    priceByQuote: "Request quote",
    stock: "Stock",
    verify: "Verify",
    condition: "Condition",
    packaging: "Packaging",
    origin: "Origin",
    leadTime: "Lead time",
    days: "days",
    view: "View",
    add: "Add",
    addToCart: "Add to cart",
    saveFavorite: "Save favorite",
    compare: "Compare product",
    datasheet: "Datasheet",
    viewSource: "View product source",
    share: "Share",
  },
  cart: {
    label: "Cart",
    eyebrow: "Quicksol checkout",
    title: "Shopping cart",
    body: "Review your products and enter the delivery details. Online payment will be connected when Stripe is configured.",
    added: "Product added to your cart.",
    emptyTitle: "Your cart is empty",
    emptyBody: "Add products from the catalog to prepare your order.",
    continueShopping: "Continue shopping",
    quantity: "Quantity",
    remove: "Remove",
    estimatedSubtotal: "Estimated subtotal",
    quoteRequired: "Some prices require a final quotation.",
    item: "item",
    items: "items",
    formTitle: "Purchase information",
    formBody:
      "Complete this form now. Your details will remain saved on this device until online payment is enabled.",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    phone: "Phone",
    company: "Company",
    country: "Country",
    address: "Delivery address",
    city: "City",
    postalCode: "Postal code",
    notes: "Order notes",
    submit: "Save order details",
    success:
      "Your order details were saved. Online payment will be available when Stripe is connected.",
  },
};

const copies: Record<Locale, CommerceCopy> = {
  en,
  es: {
    catalog: {
      ...en.catalog,
      metaTitle: "Catálogo global de Quicksol",
      metaDescription:
        "Busca componentes electrónicos publicados por MPN, SKU, marca, categoría y disponibilidad.",
      eyebrow: "Productos",
      title: "Catálogo de componentes electrónicos",
      body: "Explora 500 referencias reales de fabricantes líderes. Los precios unitarios son estimaciones de mercado y se confirman mediante cotización.",
      results: "resultados",
      configuredTitle: "El catálogo requiere configuración",
      configuredBody:
        "El catálogo de productos no está disponible temporalmente. Inténtalo nuevamente en unos minutos.",
      errorTitle: "No se pudo cargar el catálogo",
      errorBody:
        "El servicio del catálogo no está disponible temporalmente. Inténtalo de nuevo o solicita una cotización con el número de parte exacto.",
      emptyTitle: "Ningún producto coincide con esta búsqueda",
      emptyBody:
        "Limpia uno o más filtros o solicita una cotización para el número de parte exacto.",
      filters: {
        searchLabel: "Buscar en el catálogo",
        searchPlaceholder: "Buscar MPN, SKU o fabricante",
        brand: "Marca",
        allBrands: "Todas las marcas",
        category: "Categoría",
        allCategories: "Todas las categorías",
        availability: "Disponibilidad",
        anyStock: "Cualquier stock",
        inStock: "En stock",
        limited: "Limitado",
        quote: "Bajo pedido",
        condition: "Condición",
        anyCondition: "Cualquier condición",
        new: "Nuevo",
        refurbished: "Reacondicionado",
        surplus: "Excedente",
        sort: "Ordenar",
        relevance: "Relevancia",
        alphabetical: "Alfabético",
        price: "Precio",
        search: "Buscar",
        clear: "Limpiar",
      },
      pagination: {
        label: "Paginación del catálogo",
        previous: "Anterior",
        next: "Siguiente",
      },
    },
    product: {
      ...en.product,
      product: "Producto",
      publishedProduct: "Producto publicado en el catálogo.",
      requestQuote: "Solicitar cotización",
      contactTeam: "Contactar al equipo",
      configuredTitle: "El catálogo requiere configuración",
      configuredBody:
        "Los detalles del producto no están disponibles temporalmente. Inténtalo nuevamente.",
      errorTitle: "No se pudo cargar el producto",
      referencePhoto: "Foto real de referencia del encapsulado",
      technicalSpecifications: "Especificaciones técnicas",
      specificationsPending:
        "Las especificaciones aún no están publicadas. Solicita una cotización para recibir detalles técnicos verificados.",
      estimatedPrice: "Precio unitario estimado",
      estimatedPriceBody:
        "Precio unitario estimado en USD. Confirma precio final, stock y envío mediante cotización.",
      featured: "Destacado",
      fallbackDescription: "Detalles técnicos disponibles bajo solicitud.",
      priceByQuote: "Solicitar cotización",
      stock: "Stock",
      verify: "Verificar",
      condition: "Condición",
      packaging: "Empaque",
      origin: "Origen",
      leadTime: "Tiempo de entrega",
      days: "días",
      view: "Ver",
      add: "Añadir",
      addToCart: "Añadir al carrito",
      saveFavorite: "Guardar favorito",
      compare: "Comparar producto",
      datasheet: "Ficha técnica",
      viewSource: "Ver fuente del producto",
      share: "Compartir",
    },
    cart: {
      ...en.cart,
      label: "Carrito",
      eyebrow: "Compra Quicksol",
      title: "Carrito de compras",
      body: "Revisa tus productos e ingresa los datos de entrega. El pago en línea se conectará cuando Stripe esté configurado.",
      added: "Producto añadido a tu carrito.",
      emptyTitle: "Tu carrito está vacío",
      emptyBody: "Añade productos desde el catálogo para preparar tu compra.",
      continueShopping: "Seguir comprando",
      quantity: "Cantidad",
      remove: "Eliminar",
      estimatedSubtotal: "Subtotal estimado",
      quoteRequired: "Algunos precios requieren una cotización final.",
      item: "producto",
      items: "productos",
      formTitle: "Información de compra",
      formBody:
        "Completa este formulario ahora. Tus datos quedarán guardados en este dispositivo hasta habilitar el pago en línea.",
      firstName: "Nombre",
      lastName: "Apellido",
      email: "Correo electrónico",
      phone: "Teléfono",
      company: "Empresa",
      country: "País",
      address: "Dirección de entrega",
      city: "Ciudad",
      postalCode: "Código postal",
      notes: "Notas del pedido",
      submit: "Guardar datos de compra",
      success:
        "Tus datos de compra quedaron guardados. El pago en línea estará disponible cuando se conecte Stripe.",
    },
  },
  zh: {
    catalog: {
      ...en.catalog,
      metaTitle: "Quicksol 全球产品目录",
      metaDescription: "按 MPN、SKU、品牌、类别和供货状态搜索电子元器件。",
      eyebrow: "产品",
      title: "电子元器件目录",
      body: "浏览 500 个真实制造商料号。单价为市场估算，最终以报价为准。",
      results: "个结果",
      configuredTitle: "产品目录暂不可用",
      configuredBody: "产品目录暂时无法使用，请稍后再试。",
      errorTitle: "无法加载产品目录",
      errorBody: "目录服务暂时不可用。请重试或使用准确的制造商料号申请报价。",
      emptyTitle: "没有符合条件的产品",
      emptyBody: "请清除部分筛选条件，或使用准确料号申请报价。",
      filters: {
        searchLabel: "搜索目录",
        searchPlaceholder: "搜索 MPN、SKU 或制造商",
        brand: "品牌",
        allBrands: "所有品牌",
        category: "类别",
        allCategories: "所有类别",
        availability: "供货状态",
        anyStock: "所有库存",
        inStock: "有库存",
        limited: "库存有限",
        quote: "按需供应",
        condition: "状态",
        anyCondition: "所有状态",
        new: "全新",
        refurbished: "翻新",
        surplus: "库存余量",
        sort: "排序",
        relevance: "相关性",
        alphabetical: "字母顺序",
        price: "价格",
        search: "搜索",
        clear: "清除",
      },
      pagination: { label: "目录分页", previous: "上一页", next: "下一页" },
    },
    product: {
      ...en.product,
      product: "产品",
      publishedProduct: "已发布的目录产品。",
      requestQuote: "申请报价",
      contactTeam: "联系团队",
      configuredTitle: "产品目录暂不可用",
      configuredBody: "产品详情暂时无法使用，请稍后再试。",
      errorTitle: "无法加载产品",
      referencePhoto: "真实封装参考图片",
      technicalSpecifications: "技术规格",
      specificationsPending: "技术规格尚未发布。请申请报价以获取已验证的详情。",
      estimatedPrice: "预估单价",
      estimatedPriceBody: "美元预估单价。最终价格、库存和运费以报价为准。",
      featured: "精选",
      fallbackDescription: "技术详情可按需提供。",
      priceByQuote: "申请报价",
      stock: "库存",
      verify: "待确认",
      condition: "状态",
      packaging: "包装",
      origin: "原产地",
      leadTime: "交货期",
      days: "天",
      view: "查看",
      add: "加入",
      addToCart: "加入购物车",
      saveFavorite: "收藏",
      compare: "比较产品",
      datasheet: "数据手册",
      viewSource: "查看产品来源",
      share: "分享",
    },
    cart: {
      ...en.cart,
      label: "购物车",
      eyebrow: "Quicksol 结算",
      title: "购物车",
      body: "核对产品并填写配送信息。配置 Stripe 后将启用在线支付。",
      added: "产品已加入购物车。",
      emptyTitle: "购物车为空",
      emptyBody: "从产品目录中添加产品以准备订单。",
      continueShopping: "继续购物",
      quantity: "数量",
      remove: "删除",
      estimatedSubtotal: "预估小计",
      quoteRequired: "部分价格需要最终报价。",
      item: "件产品",
      items: "件产品",
      formTitle: "购买信息",
      formBody: "请填写此表单。启用在线支付前，信息将保存在此设备上。",
      firstName: "名字",
      lastName: "姓氏",
      email: "电子邮箱",
      phone: "电话",
      company: "公司",
      country: "国家/地区",
      address: "配送地址",
      city: "城市",
      postalCode: "邮政编码",
      notes: "订单备注",
      submit: "保存订单信息",
      success: "订单信息已保存。连接 Stripe 后即可在线支付。",
    },
  },
  fr: {
    catalog: {
      ...en.catalog,
      metaTitle: "Catalogue mondial Quicksol",
      metaDescription:
        "Recherchez des composants électroniques par MPN, SKU, marque, catégorie et disponibilité.",
      eyebrow: "Produits",
      title: "Catalogue de composants électroniques",
      body: "Explorez 500 références réelles de fabricants. Les prix unitaires sont des estimations de marché confirmées par devis.",
      results: "résultats",
      configuredTitle: "Catalogue temporairement indisponible",
      configuredBody: "Le catalogue produits est temporairement indisponible. Réessayez bientôt.",
      errorTitle: "Impossible de charger le catalogue",
      errorBody: "Le service catalogue est indisponible. Réessayez ou demandez un devis avec la référence exacte.",
      emptyTitle: "Aucun produit ne correspond",
      emptyBody: "Effacez certains filtres ou demandez un devis pour la référence exacte.",
      filters: {
        searchLabel: "Rechercher dans le catalogue",
        searchPlaceholder: "Rechercher MPN, SKU ou fabricant",
        brand: "Marque",
        allBrands: "Toutes les marques",
        category: "Catégorie",
        allCategories: "Toutes les catégories",
        availability: "Disponibilité",
        anyStock: "Tout stock",
        inStock: "En stock",
        limited: "Limité",
        quote: "Sur demande",
        condition: "État",
        anyCondition: "Tout état",
        new: "Neuf",
        refurbished: "Reconditionné",
        surplus: "Surplus",
        sort: "Trier",
        relevance: "Pertinence",
        alphabetical: "Alphabétique",
        price: "Prix",
        search: "Rechercher",
        clear: "Effacer",
      },
      pagination: { label: "Pagination du catalogue", previous: "Précédent", next: "Suivant" },
    },
    product: {
      ...en.product,
      product: "Produit",
      publishedProduct: "Produit publié au catalogue.",
      requestQuote: "Demander un devis",
      contactTeam: "Contacter l’équipe",
      configuredTitle: "Catalogue temporairement indisponible",
      configuredBody: "Les détails du produit sont temporairement indisponibles.",
      errorTitle: "Impossible de charger le produit",
      referencePhoto: "Photo réelle de référence du boîtier",
      technicalSpecifications: "Spécifications techniques",
      specificationsPending: "Les spécifications ne sont pas encore publiées. Demandez un devis pour les détails vérifiés.",
      estimatedPrice: "Prix unitaire estimé",
      estimatedPriceBody: "Prix unitaire estimé en USD. Confirmez prix, stock et transport par devis.",
      featured: "En vedette",
      fallbackDescription: "Détails techniques disponibles sur demande.",
      priceByQuote: "Demander un devis",
      stock: "Stock",
      verify: "À vérifier",
      condition: "État",
      packaging: "Emballage",
      origin: "Origine",
      leadTime: "Délai",
      days: "jours",
      view: "Voir",
      add: "Ajouter",
      addToCart: "Ajouter au panier",
      saveFavorite: "Enregistrer",
      compare: "Comparer",
      datasheet: "Fiche technique",
      viewSource: "Voir la source du produit",
      share: "Partager",
    },
    cart: {
      ...en.cart,
      label: "Panier",
      eyebrow: "Commande Quicksol",
      title: "Panier",
      body: "Vérifiez vos produits et saisissez les informations de livraison. Le paiement en ligne sera activé avec Stripe.",
      added: "Produit ajouté au panier.",
      emptyTitle: "Votre panier est vide",
      emptyBody: "Ajoutez des produits du catalogue pour préparer votre commande.",
      continueShopping: "Continuer les achats",
      quantity: "Quantité",
      remove: "Supprimer",
      estimatedSubtotal: "Sous-total estimé",
      quoteRequired: "Certains prix nécessitent un devis final.",
      item: "article",
      items: "articles",
      formTitle: "Informations d’achat",
      formBody: "Complétez ce formulaire. Vos informations resteront enregistrées sur cet appareil jusqu’à l’activation du paiement.",
      firstName: "Prénom",
      lastName: "Nom",
      email: "E-mail",
      phone: "Téléphone",
      company: "Entreprise",
      country: "Pays",
      address: "Adresse de livraison",
      city: "Ville",
      postalCode: "Code postal",
      notes: "Notes de commande",
      submit: "Enregistrer la commande",
      success: "Vos informations sont enregistrées. Le paiement sera disponible après connexion de Stripe.",
    },
  },
  de: {
    catalog: {
      ...en.catalog,
      metaTitle: "Quicksol Global Katalog",
      metaDescription: "Elektronische Bauteile nach MPN, SKU, Marke, Kategorie und Verfügbarkeit suchen.",
      eyebrow: "Produkte",
      title: "Katalog für elektronische Bauteile",
      body: "Entdecken Sie 500 reale Herstellerreferenzen. Stückpreise sind Marktschätzungen und werden per Angebot bestätigt.",
      results: "Ergebnisse",
      configuredTitle: "Katalog vorübergehend nicht verfügbar",
      configuredBody: "Der Produktkatalog ist vorübergehend nicht verfügbar. Bitte versuchen Sie es später erneut.",
      errorTitle: "Katalog konnte nicht geladen werden",
      errorBody: "Der Katalogdienst ist vorübergehend nicht verfügbar. Versuchen Sie es erneut oder senden Sie eine Anfrage mit exakter Teilenummer.",
      emptyTitle: "Keine passenden Produkte",
      emptyBody: "Entfernen Sie Filter oder fordern Sie ein Angebot für die exakte Teilenummer an.",
      filters: {
        searchLabel: "Katalog durchsuchen",
        searchPlaceholder: "MPN, SKU oder Hersteller suchen",
        brand: "Marke",
        allBrands: "Alle Marken",
        category: "Kategorie",
        allCategories: "Alle Kategorien",
        availability: "Verfügbarkeit",
        anyStock: "Jeder Bestand",
        inStock: "Auf Lager",
        limited: "Begrenzt",
        quote: "Auf Anfrage",
        condition: "Zustand",
        anyCondition: "Jeder Zustand",
        new: "Neu",
        refurbished: "Aufbereitet",
        surplus: "Überschuss",
        sort: "Sortieren",
        relevance: "Relevanz",
        alphabetical: "Alphabetisch",
        price: "Preis",
        search: "Suchen",
        clear: "Zurücksetzen",
      },
      pagination: { label: "Katalogseiten", previous: "Zurück", next: "Weiter" },
    },
    product: {
      ...en.product,
      product: "Produkt",
      publishedProduct: "Veröffentlichtes Katalogprodukt.",
      requestQuote: "Angebot anfragen",
      contactTeam: "Team kontaktieren",
      configuredTitle: "Katalog vorübergehend nicht verfügbar",
      configuredBody: "Produktdetails sind vorübergehend nicht verfügbar.",
      errorTitle: "Produkt konnte nicht geladen werden",
      referencePhoto: "Reales Referenzfoto des Gehäuses",
      technicalSpecifications: "Technische Daten",
      specificationsPending: "Technische Daten sind noch nicht veröffentlicht. Fordern Sie verifizierte Details per Angebot an.",
      estimatedPrice: "Geschätzter Stückpreis",
      estimatedPriceBody: "Geschätzter Stückpreis in USD. Endpreis, Bestand und Versand per Angebot bestätigen.",
      featured: "Empfohlen",
      fallbackDescription: "Technische Details auf Anfrage verfügbar.",
      priceByQuote: "Angebot anfragen",
      stock: "Bestand",
      verify: "Prüfen",
      condition: "Zustand",
      packaging: "Verpackung",
      origin: "Ursprung",
      leadTime: "Lieferzeit",
      days: "Tage",
      view: "Ansehen",
      add: "Hinzufügen",
      addToCart: "In den Warenkorb",
      saveFavorite: "Favorit speichern",
      compare: "Produkt vergleichen",
      datasheet: "Datenblatt",
      viewSource: "Produktquelle ansehen",
      share: "Teilen",
    },
    cart: {
      ...en.cart,
      label: "Warenkorb",
      eyebrow: "Quicksol Bestellung",
      title: "Warenkorb",
      body: "Prüfen Sie Ihre Produkte und geben Sie die Lieferdaten ein. Online-Zahlung wird nach der Stripe-Einrichtung aktiviert.",
      added: "Produkt wurde zum Warenkorb hinzugefügt.",
      emptyTitle: "Ihr Warenkorb ist leer",
      emptyBody: "Fügen Sie Produkte aus dem Katalog hinzu.",
      continueShopping: "Weiter einkaufen",
      quantity: "Menge",
      remove: "Entfernen",
      estimatedSubtotal: "Geschätzte Zwischensumme",
      quoteRequired: "Einige Preise benötigen ein finales Angebot.",
      item: "Artikel",
      items: "Artikel",
      formTitle: "Kaufinformationen",
      formBody: "Füllen Sie das Formular aus. Die Angaben bleiben bis zur Aktivierung der Online-Zahlung auf diesem Gerät gespeichert.",
      firstName: "Vorname",
      lastName: "Nachname",
      email: "E-Mail",
      phone: "Telefon",
      company: "Unternehmen",
      country: "Land",
      address: "Lieferadresse",
      city: "Stadt",
      postalCode: "Postleitzahl",
      notes: "Bestellnotizen",
      submit: "Bestelldaten speichern",
      success: "Ihre Bestelldaten wurden gespeichert. Die Online-Zahlung folgt nach der Stripe-Anbindung.",
    },
  },
  ja: {
    catalog: {
      ...en.catalog,
      metaTitle: "Quicksol Global 製品カタログ",
      metaDescription: "MPN、SKU、ブランド、カテゴリ、在庫状況から電子部品を検索できます。",
      eyebrow: "製品",
      title: "電子部品カタログ",
      body: "実在するメーカー品番500点を掲載。単価は市場推定値で、最終価格は見積りで確定します。",
      results: "件",
      configuredTitle: "カタログは一時的に利用できません",
      configuredBody: "製品カタログは一時的に利用できません。しばらくしてから再度お試しください。",
      errorTitle: "カタログを読み込めませんでした",
      errorBody: "カタログサービスは一時的に利用できません。正確なメーカー品番で見積りをご依頼ください。",
      emptyTitle: "該当する製品がありません",
      emptyBody: "フィルターを解除するか、正確なメーカー品番で見積りをご依頼ください。",
      filters: {
        searchLabel: "カタログ検索",
        searchPlaceholder: "MPN、SKU、メーカーを検索",
        brand: "ブランド",
        allBrands: "すべてのブランド",
        category: "カテゴリ",
        allCategories: "すべてのカテゴリ",
        availability: "在庫状況",
        anyStock: "すべての在庫",
        inStock: "在庫あり",
        limited: "残りわずか",
        quote: "要問い合わせ",
        condition: "状態",
        anyCondition: "すべての状態",
        new: "新品",
        refurbished: "再生品",
        surplus: "余剰在庫",
        sort: "並び替え",
        relevance: "関連度",
        alphabetical: "アルファベット順",
        price: "価格",
        search: "検索",
        clear: "クリア",
      },
      pagination: { label: "カタログページ", previous: "前へ", next: "次へ" },
    },
    product: {
      ...en.product,
      product: "製品",
      publishedProduct: "公開カタログ製品です。",
      requestQuote: "見積依頼",
      contactTeam: "担当者へ連絡",
      configuredTitle: "カタログは一時的に利用できません",
      configuredBody: "製品詳細は一時的に利用できません。",
      errorTitle: "製品を読み込めませんでした",
      referencePhoto: "実物パッケージ参考写真",
      technicalSpecifications: "技術仕様",
      specificationsPending: "仕様はまだ公開されていません。確認済みの詳細は見積りでお問い合わせください。",
      estimatedPrice: "推定単価",
      estimatedPriceBody: "USDでの推定単価です。最終価格、在庫、送料は見積りで確認してください。",
      featured: "注目製品",
      fallbackDescription: "技術詳細はお問い合わせください。",
      priceByQuote: "見積依頼",
      stock: "在庫",
      verify: "要確認",
      condition: "状態",
      packaging: "梱包",
      origin: "原産地",
      leadTime: "納期",
      days: "日",
      view: "表示",
      add: "追加",
      addToCart: "カートに追加",
      saveFavorite: "お気に入り",
      compare: "製品を比較",
      datasheet: "データシート",
      viewSource: "製品ソースを表示",
      share: "共有",
    },
    cart: {
      ...en.cart,
      label: "カート",
      eyebrow: "Quicksol ご注文",
      title: "ショッピングカート",
      body: "製品を確認し、配送情報を入力してください。Stripe設定後にオンライン決済が有効になります。",
      added: "製品をカートに追加しました。",
      emptyTitle: "カートは空です",
      emptyBody: "カタログから製品を追加して注文を準備してください。",
      continueShopping: "買い物を続ける",
      quantity: "数量",
      remove: "削除",
      estimatedSubtotal: "推定小計",
      quoteRequired: "一部の価格は最終見積りが必要です。",
      item: "点",
      items: "点",
      formTitle: "購入情報",
      formBody: "フォームを入力してください。オンライン決済が有効になるまで、この端末に保存されます。",
      firstName: "名",
      lastName: "姓",
      email: "メール",
      phone: "電話番号",
      company: "会社名",
      country: "国",
      address: "配送先住所",
      city: "市区町村",
      postalCode: "郵便番号",
      notes: "注文メモ",
      submit: "注文情報を保存",
      success: "注文情報を保存しました。Stripe接続後にオンライン決済を利用できます。",
    },
  },
  ko: {
    catalog: {
      ...en.catalog,
      metaTitle: "Quicksol Global 제품 카탈로그",
      metaDescription: "MPN, SKU, 브랜드, 카테고리 및 재고 상태로 전자부품을 검색하세요.",
      eyebrow: "제품",
      title: "전자부품 카탈로그",
      body: "실제 제조사 부품 500개를 확인하세요. 단가는 시장 추정치이며 최종 견적으로 확정됩니다.",
      results: "개 결과",
      configuredTitle: "카탈로그를 일시적으로 사용할 수 없습니다",
      configuredBody: "제품 카탈로그를 일시적으로 사용할 수 없습니다. 잠시 후 다시 시도하세요.",
      errorTitle: "카탈로그를 불러올 수 없습니다",
      errorBody: "카탈로그 서비스를 일시적으로 사용할 수 없습니다. 정확한 제조사 부품 번호로 견적을 요청하세요.",
      emptyTitle: "검색 조건과 일치하는 제품이 없습니다",
      emptyBody: "필터를 해제하거나 정확한 부품 번호로 견적을 요청하세요.",
      filters: {
        searchLabel: "카탈로그 검색",
        searchPlaceholder: "MPN, SKU 또는 제조사 검색",
        brand: "브랜드",
        allBrands: "모든 브랜드",
        category: "카테고리",
        allCategories: "모든 카테고리",
        availability: "재고 상태",
        anyStock: "모든 재고",
        inStock: "재고 있음",
        limited: "한정 수량",
        quote: "문의 필요",
        condition: "상태",
        anyCondition: "모든 상태",
        new: "신품",
        refurbished: "리퍼비시",
        surplus: "잉여 재고",
        sort: "정렬",
        relevance: "관련도",
        alphabetical: "가나다순",
        price: "가격",
        search: "검색",
        clear: "초기화",
      },
      pagination: { label: "카탈로그 페이지", previous: "이전", next: "다음" },
    },
    product: {
      ...en.product,
      product: "제품",
      publishedProduct: "공개 카탈로그 제품입니다.",
      requestQuote: "견적 요청",
      contactTeam: "팀에 문의",
      configuredTitle: "카탈로그를 일시적으로 사용할 수 없습니다",
      configuredBody: "제품 상세 정보를 일시적으로 사용할 수 없습니다.",
      errorTitle: "제품을 불러올 수 없습니다",
      referencePhoto: "실제 패키지 참고 사진",
      technicalSpecifications: "기술 사양",
      specificationsPending: "사양이 아직 공개되지 않았습니다. 확인된 세부 정보는 견적으로 문의하세요.",
      estimatedPrice: "예상 단가",
      estimatedPriceBody: "USD 예상 단가입니다. 최종 가격, 재고 및 배송비는 견적으로 확인하세요.",
      featured: "추천",
      fallbackDescription: "기술 정보는 요청 시 제공됩니다.",
      priceByQuote: "견적 요청",
      stock: "재고",
      verify: "확인 필요",
      condition: "상태",
      packaging: "포장",
      origin: "원산지",
      leadTime: "납기",
      days: "일",
      view: "보기",
      add: "추가",
      addToCart: "장바구니에 추가",
      saveFavorite: "즐겨찾기",
      compare: "제품 비교",
      datasheet: "데이터시트",
      viewSource: "제품 출처 보기",
      share: "공유",
    },
    cart: {
      ...en.cart,
      label: "장바구니",
      eyebrow: "Quicksol 주문",
      title: "장바구니",
      body: "제품을 확인하고 배송 정보를 입력하세요. Stripe 설정 후 온라인 결제가 활성화됩니다.",
      added: "제품을 장바구니에 추가했습니다.",
      emptyTitle: "장바구니가 비어 있습니다",
      emptyBody: "카탈로그에서 제품을 추가해 주문을 준비하세요.",
      continueShopping: "쇼핑 계속하기",
      quantity: "수량",
      remove: "삭제",
      estimatedSubtotal: "예상 소계",
      quoteRequired: "일부 가격은 최종 견적이 필요합니다.",
      item: "개 제품",
      items: "개 제품",
      formTitle: "구매 정보",
      formBody: "양식을 작성하세요. 온라인 결제가 활성화될 때까지 이 기기에 저장됩니다.",
      firstName: "이름",
      lastName: "성",
      email: "이메일",
      phone: "전화번호",
      company: "회사",
      country: "국가",
      address: "배송 주소",
      city: "도시",
      postalCode: "우편번호",
      notes: "주문 메모",
      submit: "주문 정보 저장",
      success: "주문 정보가 저장되었습니다. Stripe 연결 후 온라인 결제를 사용할 수 있습니다.",
    },
  },
};

export function getCommerceCopy(locale: Locale) {
  return copies[locale] || copies.en;
}
